apiVersion: apps/v1
kind: Deployment
metadata:
  name: indore-finance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indore-finance-service
  template:
    metadata:
      labels:
        app: indore-finance-service
    spec:
      containers:
        - name: indore-finance-service
          image: vinaysunhare/indore-finance-service:latest
          imagePullPolicy: Never  # 🚨 Yeh bahut zaroori hai agar tu local image use kar raha
          ports:
            - containerPort: 5000
