apiVersion: v1
kind: Service
metadata:
  name: indore-finance-service
spec:
  selector:
    app: indore-finance-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
